---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check example script
      ansible.builtin.stat:
        path: /usr/local/bin/example_script
      register: example_stat
    - name: Check that example script is a file
      ansible.builtin.assert:
        that: example_stat.stat.isreg
